CREATE TABLE BILHETE (
    COD_BILHETE INTEGER CONSTRAINT PK_COD_BILHETE PRIMARY KEY,
    DATA_HORA_GERACAO_BILHETE TIMESTAMP
);

CREATE TABLE RECARGA (
    COD_RECARGA INTEGER CONSTRAINT PK_COD_RECARGA PRIMARY KEY,
    DATA_HORA_RECARGA TIMESTAMP,
    TIPO_RECARGA VARCHAR2(10),
    CHECK_RECARGA INTEGER, --0 = FALSE or 1 = TRUE
    QTD_RECARGA INTEGER,   --1, 2 or 0
    FK_BILHETE_COD INTEGER,
    FOREIGN KEY (FK_BILHETE_COD) REFERENCES BILHETE (COD_BILHETE)
);

CREATE SEQUENCE SEQUENCE_COD_RECARGA MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1;

CREATE TRIGGER TRIGGER_COD_RECARGA BEFORE
    INSERT ON RECARGA FOR EACH ROW
BEGIN
    SELECT
        "SEQUENCE_COD_RECARGA".NEXTVAL INTO:NEW.COD_RECARGA
    FROM
        DUAL;
END TRIGGER_COD_RECARGA;

CREATE TABLE UTILIZACAO (
    COD_UTILIZACAO INTEGER CONSTRAINT PK_COD_UTILIZACAO PRIMARY KEY,
    DATA_HORA_INICIAL_UTILIZACAO TIMESTAMP,
    DATA_HORA_UTILIZACAO TIMESTAMP,
    FK_RECARGA_COD INTEGER,
    FOREIGN KEY (FK_RECARGA_COD) REFERENCES RECARGA (COD_RECARGA)
);

CREATE SEQUENCE SEQUENCE_COD_UTILIZACAO MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1;

CREATE TRIGGER TRIGGER_COD_UTILIZACAO BEFORE
    INSERT ON UTILIZACAO FOR EACH ROW
BEGIN
    SELECT
        "SEQUENCE_COD_UTILIZACAO".NEXTVAL INTO:NEW.COD_UTILIZACAO
    FROM
        DUAL;
END TRIGGER_COD_UTILIZACAO;

INSERT INTO BILHETE VALUES (
    0,
    SYSTIMESTAMP(0)
);

SELECT
    BILHETE.COD_BILHETE,
    BILHETE.DATA_GERACAO_BILHETE,
    RECARGA.COD_RECARGA,
    RECARGA.DATA_HORA_RECARGA,
    RECARGA.TIPO_RECARGA
    RECARGA.CHECK_RECARGA,
    RECARGA.NUM_RECARGA,
    UTILIZACAO.COD_UTILIZACAO,
    UTILIZACAO.DATA_HORA_UTILIZACAO

FROM
    BILHETE
    JOIN RECARGA
    ON BILHETE.COD_BILHETE = RECARGA.FK_BILHETE_COD
    JOIN UTILIZACAO
    ON RECARGA.COD_RECARGA = UTILIZACAO.FK_RECARGA_COD;

SELECT BILHETE.COD_BILHETE, BILHETE.DATA_HORA_GERACAO_BILHETE, RECARGA.DATA_HORA_RECARGA, RECARGA.TIPO_RECARGA, UTILIZACAO.COD_UTILIZACAO, UTILIZACAO.DATA_HORA_UTILIZACAO FROM BILHETE JOIN RECARGA ON BILHETE.COD_BILHETE = RECARGA.FK_BILHETE_COD JOIN UTILIZACAO ON RECARGA.COD_RECARGA = UTILIZACAO.FK_RECARGA_COD WHERE BILHETE.COD_BILHETE IN (:0) ORDER BY UTILIZACAO.DATA_HORA_UTILIZACAO DESC;

SELECT * from Bilhete;
SELECT * from Recarga;
SELECT * from Utilizacao;

DROP TRIGGER TRIGGER_COD_UTILIZACAO;
DROP SEQUENCE SEQUENCE_COD_UTILIZACAO;
DROP TABLE Utilizacao;
DROP TRIGGER TRIGGER_COD_RECARGA;
DROP SEQUENCE SEQUENCE_COD_RECARGA;
DROP TABLE Recarga;
DROP TABLE Bilhete;

INSERT INTO BILHETE VALUES(0, SYSTIMESTAMP(0));

CREATE TABLE Recarga (
    cod_recarga integer CONSTRAINT pk_COD_RECARGA PRIMARY KEY,
    data_hora_recarga timestamp,
    tipo_recarga varchar2(10),
    check_recarga number(1),
    qtd_recarga number(1),
    fk_BILHETE_cod integer,
    FOREIGN KEY (fk_BILHETE_cod) REFERENCES Bilhete (cod_bilhete)
)

UPDATE Recarga SET check_recarga = 0 WHERE cod_recarga = 1;